import = ["/home/nikola/.config/alacritty/alacritty-theme/themes/tokyo-night.toml"]

[font]
size = 12.0

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[shell]
program = "/bin/zsh"
