import = ["/home/nikola/.config/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"]

[font]
size = 15.0

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Regular"

#[window]
#opacity = 0.5

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"
